// This is data that has been transformed from WSJNav data to match the props of the EditionPicker

export default {
  'na,us': {
    homepages: [
      {
        index: 0,
        region: 'na,us',
        label: 'English',
        mobileURL: '/',
        desktopURL: '/',
        url: '/',
        chineseLabel: 'English',
        isCurrentRegion: true,
      },
      {
        index: 1,
        region: 'asia,cn',
        label: '中文 (Chinese) ',
        mobileURL: 'https://cn.s.dev.wsj.com/zh-hans',
        desktopURL: 'https://cn.s.dev.wsj.com/zh-hans',
        url: 'https://cn.s.dev.wsj.com/zh-hans',
        chineseLabel: '中文 (Chinese) ',
        isCurrentRegion: false,
      },
      {
        index: 2,
        region: 'asia,jp',
        label: '日本語 (Japanese)',
        mobileURL: 'https://jp.wsj.com/',
        desktopURL: 'https://jp.wsj.com/',
        url: 'https://jp.wsj.com/',
        chineseLabel: '日本語 (Japanese)',
        isCurrentRegion: false,
      },
    ],
    region: 'na,us',
    currentEditionLabel: 'English Edition',
  },
  'asia,cn': {
    homepages: [
      {
        index: 0,
        region: 'na,us',
        label: 'English',
        mobileURL: '/',
        desktopURL: '/',
        url: '/',
        chineseLabel: 'English',
        isCurrentRegion: false,
      },
      {
        index: 1,
        region: 'asia,cn',
        label: '中文 (Chinese) ',
        mobileURL: 'https://cn.s.dev.wsj.com/zh-hans',
        desktopURL: 'https://cn.s.dev.wsj.com/zh-hans',
        url: 'https://cn.s.dev.wsj.com/zh-hans',
        chineseLabel: '简体版',
        isCurrentRegion: true,
      },
      {
        index: 2,
        region: 'asia,jp',
        label: '日本語 (Japanese)',
        mobileURL: 'https://jp.wsj.com/',
        desktopURL: 'https://jp.wsj.com/',
        url: 'https://jp.wsj.com/',
        chineseLabel: '日本語 (Japanese)',
        isCurrentRegion: false,
      },
      {
        index: 3,
        region: 'asia,cn_hant',
        label: '中文 (Chinese) ',
        mobileURL: 'http://cn.s.dev.wsj.com/zh-hant',
        desktopURL: 'http://cn.s.dev.wsj.com/zh-hant',
        url: 'http://cn.s.dev.wsj.com/zh-hant',
        chineseLabel: '繁體版',
        isCurrentRegion: false,
      },
    ],
    region: 'asia,cn',
    currentEditionLabel: '简体版',
  },
  'asia,jp': {
    homepages: [
      {
        index: 0,
        region: 'na,us',
        label: 'English',
        mobileURL: '/',
        desktopURL: '/',
        url: '/',
        chineseLabel: 'English',
        isCurrentRegion: false,
      },
      {
        index: 1,
        region: 'asia,cn',
        label: '中文 (Chinese) ',
        mobileURL: 'https://cn.s.dev.wsj.com/zh-hans',
        desktopURL: 'https://cn.s.dev.wsj.com/zh-hans',
        url: 'https://cn.s.dev.wsj.com/zh-hans',
        chineseLabel: '中文 (Chinese) ',
        isCurrentRegion: false,
      },
      {
        index: 2,
        region: 'asia,jp',
        label: '日本語 (Japanese)',
        mobileURL: 'https://jp.wsj.com/',
        desktopURL: 'https://jp.wsj.com/',
        url: 'https://jp.wsj.com/',
        chineseLabel: '日本語 (Japanese)',
        isCurrentRegion: true,
      },
    ],
    region: 'asia,jp',
    currentEditionLabel: '日本語 (Japanese)',
  },
  'asia,cn_hant': {
    homepages: [
      {
        index: 0,
        region: 'na,us',
        label: 'English',
        mobileURL: '/',
        desktopURL: '/',
        url: '/',
        chineseLabel: 'English',
        isCurrentRegion: false,
      },
      {
        index: 1,
        region: 'asia,cn',
        label: '中文 (Chinese) ',
        mobileURL: 'https://cn.s.dev.wsj.com/zh-hans',
        desktopURL: 'https://cn.s.dev.wsj.com/zh-hans',
        url: 'https://cn.s.dev.wsj.com/zh-hans',
        chineseLabel: '简体版',
        isCurrentRegion: false,
      },
      {
        index: 2,
        region: 'asia,jp',
        label: '日本語 (Japanese)',
        mobileURL: 'https://jp.wsj.com/',
        desktopURL: 'https://jp.wsj.com/',
        url: 'https://jp.wsj.com/',
        chineseLabel: '日本語 (Japanese)',
        isCurrentRegion: false,
      },
      {
        index: 3,
        region: 'asia,cn_hant',
        label: '中文 (Chinese) ',
        mobileURL: 'http://cn.s.dev.wsj.com/zh-hant',
        desktopURL: 'http://cn.s.dev.wsj.com/zh-hant',
        url: 'http://cn.s.dev.wsj.com/zh-hant',
        chineseLabel: '繁體版',
        isCurrentRegion: true,
      },
    ],
    region: 'asia,cn_hant',
    currentEditionLabel: '繁體版',
  },
};
