# When a PR is labeled, check to see if its one of our special labels and trigger the corresponding workflow

name: PR Label Handler

on:
  pull_request:
    types: [labeled]

jobs:
  trigger_pr_deploy:

    # only deploy the PR if it has our very special 'deploy' label
    if: ${{ github.event.label.name == 'deploy' }}
    name: PR Deploy Trigger
    runs-on: ubuntu-latest

    steps:
      - name: trigger pr deployer
        uses: peter-evans/repository-dispatch@v1
        with:
          event-type: deploy-pr
          token: ${{ secrets.BOT_TOKEN }}
          client-payload: '{ "ref": "${{ github.ref }}", "branch": "${{ github.head_ref }}", "pr_number": "${{ github.event.pull_request.number }}" }'
