name: dispatch

on:
  workflow_dispatch:
    inputs:
      packages: 
        description: 'which packages to release'
        required: true
      
jobs:
  main:
    outputs:
      packages: ${{ steps.parse.outputs.packages }}
    runs-on: ubuntu-latest
    
    steps:
      - id: parse
        run: echo "::set-output name=packages::$(jq -c split(",") | map(gsub(" ";"")) <<< "${{ github.event.inputs.packages }}")"
  
  matrix:
    needs: main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJSON(needs.main.outputs.packages) }}
    steps:
      - run: echo "${{ matrix.package }}"
